# --- ส่วนของ REVERSE PROXY ---
ProxyPass /api http://backend:5000/api
ProxyPassReverse /api http://backend:5000/api

<Directory "/usr/local/apache2/htdocs">
    # สำหรับ React Router
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.html$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.html [L]
    
    AllowOverride All
    Require all granted
</Directory>