"""

Revision ID: 057961d8f465
Revises: 84e15306d59f
Create Date: 2026-02-24 16:23:42.382918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '057961d8f465'
down_revision = '84e15306d59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.alter_column('sensor_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.alter_column('sensor_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
