"""

Revision ID: 05dc9d7499af
Revises: 
Create Date: 2026-02-20 13:43:31.091209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05dc9d7499af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('serial_no_a', sa.String(length=100), nullable=False),
    sa.Column('serial_no_b', sa.String(length=100), nullable=False),
    sa.Column('4.5_1', sa.Float(), nullable=False),
    sa.Column('4.5_2', sa.Float(), nullable=False),
    sa.Column('4.5_3', sa.Float(), nullable=False),
    sa.Column('4.5_4', sa.Float(), nullable=False),
    sa.Column('5.5_5', sa.Float(), nullable=False),
    sa.Column('5.5_6', sa.Float(), nullable=False),
    sa.Column('5.5_7', sa.Float(), nullable=False),
    sa.Column('5.5_8', sa.Float(), nullable=False),
    sa.Column('50_a', sa.Float(), nullable=False),
    sa.Column('49.6_a', sa.Float(), nullable=False),
    sa.Column('50_b', sa.Float(), nullable=False),
    sa.Column('60_b', sa.Float(), nullable=False),
    sa.Column('141_b', sa.Float(), nullable=False),
    sa.Column('43.8_b', sa.Float(), nullable=False),
    sa.Column('4.5_1_2', sa.Float(), nullable=False),
    sa.Column('4.5_2_2', sa.Float(), nullable=False),
    sa.Column('4.5_3_2', sa.Float(), nullable=False),
    sa.Column('4.5_4_2', sa.Float(), nullable=False),
    sa.Column('5.5_5_2', sa.Float(), nullable=False),
    sa.Column('5.5_6_2', sa.Float(), nullable=False),
    sa.Column('5.5_7_2', sa.Float(), nullable=False),
    sa.Column('5.5_8_2', sa.Float(), nullable=False),
    sa.Column('50_a_2', sa.Float(), nullable=False),
    sa.Column('49.6_a_2', sa.Float(), nullable=False),
    sa.Column('50_b_2', sa.Float(), nullable=False),
    sa.Column('60_b_2', sa.Float(), nullable=False),
    sa.Column('141_b_2', sa.Float(), nullable=False),
    sa.Column('43.8_b_2', sa.Float(), nullable=False),
    sa.Column('result29', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tmp_duplicate', sa.Integer(), nullable=True),
    sa.Column('option_condition', sa.String(length=50), nullable=True),
    sa.Column('option_save', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serial_a', sa.String(length=100), nullable=True),
    sa.Column('serial_b', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('final_result', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_serial_a'), ['serial_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_serial_b'), ['serial_b'], unique=False)

    op.create_table('product_spec_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('point_name', sa.String(length=50), nullable=False),
    sa.Column('point_image_url', sa.String(length=255), nullable=True),
    sa.Column('nominal_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('ctrl_min_value', sa.Float(), nullable=True),
    sa.Column('ctrl_max_value', sa.Float(), nullable=True),
    sa.Column('start_value', sa.Float(), nullable=True),
    sa.Column('active_value', sa.Boolean(), nullable=True),
    sa.Column('sensor_type', sa.String(length=50), nullable=True),
    sa.Column('assigned_sensor_device_id', sa.String(length=50), nullable=True),
    sa.Column('sensor_value_key', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('point_name', sa.String(length=50), nullable=False),
    sa.Column('measured_value', sa.Float(), nullable=False),
    sa.Column('nominal_value', sa.Float(), nullable=False),
    sa.Column('upper_limit', sa.Float(), nullable=False),
    sa.Column('lower_limit', sa.Float(), nullable=False),
    sa.Column('is_pass', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurement_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_details_is_pass'), ['is_pass'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_details_measurement_id'), ['measurement_id'], unique=False)

    op.create_table('measurement_draft_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('spec_point_id', sa.Integer(), nullable=False),
    sa.Column('point_name', sa.String(length=50), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('nominal_value', sa.Float(), nullable=False),
    sa.Column('sensor_device_id', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=True),
    sa.Column('required_count', sa.Integer(), nullable=True),
    sa.Column('final_value', sa.Float(), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.ForeignKeyConstraint(['spec_point_id'], ['product_spec_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_draft_specs_measurement_id'), ['measurement_id'], unique=False)

    op.create_table('measurement_raw_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('spec_point_id', sa.Integer(), nullable=False),
    sa.Column('sensor_device_id', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.ForeignKeyConstraint(['spec_point_id'], ['product_spec_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurement_raw_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_raw_values_measurement_id'), ['measurement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_raw_values_spec_point_id'), ['spec_point_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_raw_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_raw_values_spec_point_id'))
        batch_op.drop_index(batch_op.f('ix_measurement_raw_values_measurement_id'))

    op.drop_table('measurement_raw_values')
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_draft_specs_measurement_id'))

    op.drop_table('measurement_draft_specs')
    with op.batch_alter_table('measurement_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_details_measurement_id'))
        batch_op.drop_index(batch_op.f('ix_measurement_details_is_pass'))

    op.drop_table('measurement_details')
    op.drop_table('system_settings')
    op.drop_table('product_spec_points')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_serial_b'))
        batch_op.drop_index(batch_op.f('ix_measurements_serial_a'))

    op.drop_table('measurements')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('history_records')
    # ### end Alembic commands ###
