"""

Revision ID: 06d486a154a3
Revises: 7538b935bc12
Create Date: 2026-02-22 19:13:05.668357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d486a154a3'
down_revision = '7538b935bc12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_column('stage')

    # ### end Alembic commands ###
