"""

Revision ID: 294d3c79c5d8
Revises: dce3c7dc00ca
Create Date: 2026-03-28 17:16:35.288461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294d3c79c5d8'
down_revision = 'dce3c7dc00ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_spec_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_spec_points', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
