"""

Revision ID: 52e52967e822
Revises: 057961d8f465
Create Date: 2026-02-24 20:27:33.041545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52e52967e822'
down_revision = '057961d8f465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_details', schema=None) as batch_op:
        batch_op.alter_column('point_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('measured_value',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('nominal_value',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('upper_limit',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('lower_limit',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_details', schema=None) as batch_op:
        batch_op.alter_column('lower_limit',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('upper_limit',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('nominal_value',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('measured_value',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('point_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
