"""

Revision ID: 7538b935bc12
Revises: 05dc9d7499af
Create Date: 2026-02-21 18:40:18.764660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7538b935bc12'
down_revision = '05dc9d7499af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_draft_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_active_draft_time', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'measurements', ['active_draft_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_active_draft_time')
        batch_op.drop_column('active_draft_id')

    # ### end Alembic commands ###
