"""

Revision ID: 848f4e38148a
Revises: 97fd28b4a5ec
Create Date: 2026-05-17 17:02:59.829318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848f4e38148a'
down_revision = '97fd28b4a5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_debug_mode', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('is_debug_mode')

    # ### end Alembic commands ###
