"""

Revision ID: 94144b376a4b
Revises: 848f4e38148a
Create Date: 2026-05-18 14:24:41.284567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94144b376a4b'
down_revision = '848f4e38148a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_time', mysql.DATETIME(), nullable=False),
    sa.Column('serial_no_a', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('serial_no_b', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('4.5_1', mysql.FLOAT(), nullable=False),
    sa.Column('4.5_2', mysql.FLOAT(), nullable=False),
    sa.Column('4.5_3', mysql.FLOAT(), nullable=False),
    sa.Column('4.5_4', mysql.FLOAT(), nullable=False),
    sa.Column('5.5_5', mysql.FLOAT(), nullable=False),
    sa.Column('5.5_6', mysql.FLOAT(), nullable=False),
    sa.Column('5.5_7', mysql.FLOAT(), nullable=False),
    sa.Column('5.5_8', mysql.FLOAT(), nullable=False),
    sa.Column('50_a', mysql.FLOAT(), nullable=False),
    sa.Column('49.6_a', mysql.FLOAT(), nullable=False),
    sa.Column('50_b', mysql.FLOAT(), nullable=False),
    sa.Column('60_b', mysql.FLOAT(), nullable=False),
    sa.Column('141_b', mysql.FLOAT(), nullable=False),
    sa.Column('43.8_b', mysql.FLOAT(), nullable=False),
    sa.Column('4.5_1_2', mysql.FLOAT(), nullable=False),
    sa.Column('4.5_2_2', mysql.FLOAT(), nullable=False),
    sa.Column('4.5_3_2', mysql.FLOAT(), nullable=False),
    sa.Column('4.5_4_2', mysql.FLOAT(), nullable=False),
    sa.Column('5.5_5_2', mysql.FLOAT(), nullable=False),
    sa.Column('5.5_6_2', mysql.FLOAT(), nullable=False),
    sa.Column('5.5_7_2', mysql.FLOAT(), nullable=False),
    sa.Column('5.5_8_2', mysql.FLOAT(), nullable=False),
    sa.Column('50_a_2', mysql.FLOAT(), nullable=False),
    sa.Column('49.6_a_2', mysql.FLOAT(), nullable=False),
    sa.Column('50_b_2', mysql.FLOAT(), nullable=False),
    sa.Column('60_b_2', mysql.FLOAT(), nullable=False),
    sa.Column('141_b_2', mysql.FLOAT(), nullable=False),
    sa.Column('43.8_b_2', mysql.FLOAT(), nullable=False),
    sa.Column('result29', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
