"""

Revision ID: 97fd28b4a5ec
Revises: 6b09657996f3
Create Date: 2026-05-17 15:27:15.851786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97fd28b4a5ec'
down_revision = '6b09657996f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_raw_value_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('spec_point_id', sa.Integer(), nullable=False),
    sa.Column('sensor_device_id', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.ForeignKeyConstraint(['spec_point_id'], ['product_spec_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurement_raw_value_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_raw_value_logs_measurement_id'), ['measurement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_raw_value_logs_spec_point_id'), ['spec_point_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_raw_value_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_raw_value_logs_spec_point_id'))
        batch_op.drop_index(batch_op.f('ix_measurement_raw_value_logs_measurement_id'))

    op.drop_table('measurement_raw_value_logs')
    # ### end Alembic commands ###
