"""

Revision ID: bd1ac2ce1f7c
Revises: 52e52967e822
Create Date: 2026-02-26 09:06:43.230061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1ac2ce1f7c'
down_revision = '52e52967e822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_stages', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_column('flow_stages')

    # ### end Alembic commands ###
