"""

Revision ID: c5a063eb7c08
Revises: e9fbb7e5cdae
Create Date: 2026-03-24 17:12:44.747409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a063eb7c08'
down_revision = 'e9fbb7e5cdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_value', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.drop_column('active_value')

    # ### end Alembic commands ###
