"""

Revision ID: dce3c7dc00ca
Revises: c5a063eb7c08
Create Date: 2026-03-28 16:56:03.263016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce3c7dc00ca'
down_revision = 'c5a063eb7c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
