"""

Revision ID: df4ba8e2c188
Revises: f31107a57699
Create Date: 2026-02-24 15:44:31.728873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4ba8e2c188'
down_revision = 'f31107a57699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_spec_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_spec_points', schema=None) as batch_op:
        batch_op.drop_column('rule_type')

    # ### end Alembic commands ###
