"""

Revision ID: eddeede72477
Revises: bd1ac2ce1f7c
Create Date: 2026-03-01 07:38:22.971788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eddeede72477'
down_revision = 'bd1ac2ce1f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('active_product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('active_product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
