"""

Revision ID: f31107a57699
Revises: 06d486a154a3
Create Date: 2026-02-24 15:36:01.022640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31107a57699'
down_revision = '06d486a154a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_key', sa.String(length=50), nullable=False))

    with op.batch_alter_table('product_spec_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_spec_points', schema=None) as batch_op:
        batch_op.drop_column('required_count')

    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.drop_column('value_key')

    # ### end Alembic commands ###
